services:
  mongodb:
    image: mongo:latest
    container_name: coin_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=coin_trading

  backend:
    build: ./backend
    container_name: coin_backend
    ports:
      - "5050:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/coin_trading
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: coin_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  mongodb_data: